# Site settings
title: Synaptic priming
description: primer pharmacology
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Synaptic priming
user_description: How does one plasticity event change our response to another days, weeks, or even years later? Synaptic priming provides a framework for answering this question, and can be readily applied to transform psychiatric medicine. 
user_title: A framework for the future of psychiatric medicine
email: synaptic.priming@gmail.com
twitter_username: SynapticPriming
github_username:  Synaptic-priming
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
